---
languages:
- __sardonyx__
- c
- c++
- clojure
- cplusplus
- cpp
- default
- go
- groovy
- java
- node_js
- php
- pure_java
- python
- ruby
- scala
features:
- basic
# FIXME: uncomment once working on xenial
# - cassandra
# FIXME: uncomment once working on xenial
# - couchdb
- disabled-ipv6
- docker
- docker-compose
# FIXME: uncomment once working on xenial
# - elasticsearch
- firefox
- go-toolchain
- google-chrome
- jdk
- memcached
- mongodb
- mysql
- nodejs_interpreter
- perl_interpreter
- perlbrew
- phantomjs
- postgresql
- python_interpreter
- redis
- ruby_interpreter
- sqlite
- xserver
